
server:
  port: ${DEMO_PORT:8080}
  error:
    include-stacktrace: never # don't leak stack traces to the client (thymeleaf needs to also implement /error)

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEMO_DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=demo}
    username: ${DEMO_DB_USER:postgres}
    password: ${DEMO_DB_PASS:password}
  flyway:
    locations: [classpath:db/migration, classpath:db/migration/**]
    baseline-on-migrate: true
  jpa:
    open-in-view: true  # https://www.baeldung.com/spring-open-session-in-view
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DEMO_ISSUER_URI:http://localhost:8180/realms/demo}  # must match keycloak setup
      client:
        registration:
          keycloak:
            client-id: login-app  # must match keycloak setup
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${DEMO_ISSUER_URI:http://localhost:8180/realms/demo}  # must match keycloak setup
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false  # probably don't want this in production
    mode: HTML  # reload templates and static content without restarting server
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

# swagger/openapi docs
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# logging
logging:
  file:
    name: logs/demo.log
    max-size: 30MB

# turn on actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers

# /actuator/info - show name, version, desc
info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
